# Generated by Django 6.0.1 on 2026-02-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_juststuff_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
